# Generated by Django 5.1.5 on 2026-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_dependente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "cliente",
                    models.ManyToManyField(
                        related_name="antendente_cliente", to="app.cliente"
                    ),
                ),
            ],
        ),
    ]
